import {
  BarewaService,
  BarewaAlert,
  SecuritySession,
  ActivityLog,
  AIProvider,
  EcosystemEvent,
  ServiceQueue,
  AdministratorAccount,
  SystemSettings,
} from '@/types/barewa';

export const INITIAL_SERVICES: BarewaService[] = [
  {
    id: 'srv-core-ai',
    code: 'BAREWA_AI',
    name: 'Barewa AI',
    description: "Couche d'intelligence contextuelle sahélienne, assistance multilingue (Hausa, Zarma, Français) et raisonnement distribué.",
    category: 'intelligence',
    status: 'online',
    version: 'v1.4.0',
    uptimePercent: 99.98,
    lastPingTime: 'Il y a 3s',
    endpointUrl: 'https://ai.barewa.ne/v1/router',
    connectionMode: 'REST_API',
    activeUsers24h: 3840,
    requestsPerMinute: 142,
    errorRatePercent: 0.04,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey (West-Africa)',
    tags: ['Gemini', 'Mistral', 'Ollama', 'NLP'],
  },
  {
    id: 'srv-academie',
    code: 'BAREWA_ACADEMIE',
    name: 'Barewa Académie',
    description: "Plateforme éducative, formations techniques, e-learning hors-ligne et certification pour la jeunesse du Sahel.",
    category: 'social',
    status: 'online',
    version: 'v1.1.2',
    uptimePercent: 99.92,
    lastPingTime: 'Il y a 12s',
    endpointUrl: 'https://academie.barewa.ne/api',
    connectionMode: 'REST_API',
    activeUsers24h: 12450,
    requestsPerMinute: 88,
    errorRatePercent: 0.12,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey / Zinder',
    tags: ['Éducation', 'PWA', 'Hors-ligne', 'Sahel'],
  },
  {
    id: 'srv-health',
    code: 'BAREWA_HEALTH',
    name: 'Barewa Health',
    description: "Dossier médical d'urgence, télé-orientation, carnets de vaccination et réseau d'officines pharmaceutiques de proximité.",
    category: 'social',
    status: 'online',
    version: 'v1.0.8',
    uptimePercent: 99.99,
    lastPingTime: 'Il y a 5s',
    endpointUrl: 'https://health.barewa.ne/api/v1',
    connectionMode: 'REST_API',
    activeUsers24h: 2190,
    requestsPerMinute: 34,
    errorRatePercent: 0.01,
    isMaintenance: false,
    isEnabled: true,
    region: 'Maradi / Niamey',
    tags: ['Santé', 'Sécurité Données', 'Pharmacies', 'Urgence'],
  },
  {
    id: 'srv-meteo',
    code: 'BAREWA_METEO',
    name: 'Barewa Météo',
    description: "Système agrométéorologique sahélien, prévisions pluviométriques, alertes canicule et tempêtes de sable pour agriculteurs.",
    category: 'core',
    status: 'online',
    version: 'v2.0.1',
    uptimePercent: 99.95,
    lastPingTime: 'Il y a 8s',
    endpointUrl: 'https://meteo.barewa.ne/telemetry',
    connectionMode: 'WEBSOCKET',
    activeUsers24h: 18400,
    requestsPerMinute: 210,
    errorRatePercent: 0.08,
    isMaintenance: false,
    isEnabled: true,
    region: 'Sahel Regional Grid',
    tags: ['Agrométéo', 'Alertes SMS', 'Satellites', 'Climat'],
  },
  {
    id: 'srv-store',
    code: 'BAREWA_STORE',
    name: 'Barewa Store',
    description: "Place de marché marchande sahélienne, logistique de distribution locale, paiements en FCFA et micro-commerce.",
    category: 'commerce',
    status: 'degraded',
    version: 'v0.9.4',
    uptimePercent: 98.85,
    lastPingTime: 'Il y a 45s',
    endpointUrl: 'https://store.barewa.ne/api/v2',
    connectionMode: 'REST_API',
    activeUsers24h: 5310,
    requestsPerMinute: 95,
    errorRatePercent: 2.14,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey / Tahoua',
    tags: ['E-commerce', 'Mobile Money', 'Artisanat', 'Logistique'],
  },
  {
    id: 'srv-maps',
    code: 'BAREWA_MAPS',
    name: 'Barewa Maps',
    description: "Système de géocodage descriptif, cartographie collaborative hors-ligne et points d'intérêt pour les villes et routes sahéliennes.",
    category: 'infrastructure',
    status: 'online',
    version: 'v1.0.3',
    uptimePercent: 99.91,
    lastPingTime: 'Il y a 14s',
    endpointUrl: 'https://maps.barewa.ne/tiles',
    connectionMode: 'DIRECT_DB',
    activeUsers24h: 8900,
    requestsPerMinute: 310,
    errorRatePercent: 0.05,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey Server CDN',
    tags: ['SIG', 'OpenStreetMap', 'Offline Tiles', 'Routage'],
  },
  {
    id: 'srv-mobility',
    code: 'BAREWA_MOBILITY',
    name: 'Barewa Mobility',
    description: "Plateforme de mise en relation taxi-motos, transport collectif interurbain et acheminement de colis inter-villes.",
    category: 'mobility',
    status: 'online',
    version: 'v1.2.0',
    uptimePercent: 99.88,
    lastPingTime: 'Il y a 6s',
    endpointUrl: 'https://mobility.barewa.ne/ws',
    connectionMode: 'WEBSOCKET',
    activeUsers24h: 6720,
    requestsPerMinute: 180,
    errorRatePercent: 0.15,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey & Corridors',
    tags: ['Transports', 'Géolocalisation', 'Taxis', 'Fret'],
  },
  {
    id: 'srv-jobs',
    code: 'BAREWA_JOBS',
    name: 'Barewa Jobs',
    description: "Bourse d'opportunités, mise en relation pour artisans, jeunes diplômés, missions ponctuelles et recrutement sahélien.",
    category: 'social',
    status: 'online',
    version: 'v1.0.0',
    uptimePercent: 99.90,
    lastPingTime: 'Il y a 22s',
    endpointUrl: 'https://jobs.barewa.ne/graphql',
    connectionMode: 'REST_API',
    activeUsers24h: 4120,
    requestsPerMinute: 42,
    errorRatePercent: 0.02,
    isMaintenance: false,
    isEnabled: true,
    region: 'Sahel Ouest',
    tags: ['Emploi', 'Artisans', 'Talents', 'Recrutement'],
  },
];

export const INITIAL_ALERTS: BarewaAlert[] = [
  {
    id: 'alt-01',
    title: 'Taux de latence accru sur passerelle SMS Barewa Météo',
    message: "Le relais SMS opérateur Orange/Airtel Niger accuse une latence moyenne de 12.4s pour la diffusion des alertes météo aux zones rurales.",
    severity: 'warning',
    serviceId: 'srv-meteo',
    serviceName: 'Barewa Météo',
    timestamp: '11/09/2026 10:14',
    isResolved: false,
    isAcknowledged: true,
    suggestedAction: "Basculer temporairement sur la file d'attente secondaire Moov Africa ou prioriser le canal WhatsApp/PWA.",
  },
  {
    id: 'alt-02',
    title: 'Quota horaire API Gemini Cloud à 82%',
    message: "La consommation du free-tier Google Gemini s'approche du seuil critique de 15 RPM. Le routeur IA prépare le basculement automatique.",
    severity: 'critical',
    serviceId: 'srv-core-ai',
    serviceName: 'Barewa AI',
    timestamp: '11/09/2026 09:58',
    isResolved: false,
    isAcknowledged: false,
    suggestedAction: "Activer le fallback Groq/Llama 3 ou orienter les requêtes simples vers l'instance locale Ollama.",
  },
  {
    id: 'alt-03',
    title: 'Tentative de connexion par force brute bloquée',
    message: "14 tentatives échouées sur le point d'administration en provenance de l'IP 102.164.88.12. IP temporairement bannie pour 24 heures.",
    severity: 'warning',
    serviceId: 'srv-core-security',
    serviceName: 'Barewa QG Sécurité',
    timestamp: '11/09/2026 08:30',
    isResolved: true,
    isAcknowledged: true,
    sourceIp: '102.164.88.12',
    suggestedAction: "Vérifier la politique de verrouillage d'IP et inspecter les requêtes similaires.",
  },
  {
    id: 'alt-04',
    title: 'Synchronisation PostgreSQL Supabase réussie',
    message: "La sauvegarde incrémentale et le snapshot des tables RLS ont été exécutés avec succès sans interruption de service.",
    severity: 'info',
    serviceId: 'srv-core-db',
    serviceName: 'Barewa Core Database',
    timestamp: '11/09/2026 06:00',
    isResolved: true,
    isAcknowledged: true,
  },
];

export const INITIAL_AI_PROVIDERS: AIProvider[] = [
  {
    id: 'gemini',
    name: 'Google Gemini (Native Engine)',
    providerType: 'cloud_free',
    status: 'active',
    defaultModel: 'gemini-2.5-flash',
    availableModels: ['gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemini-2.5-pro'],
    latencyMs: 340,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 15,
    currentRpm: 12,
    isConfigured: true,
    isLocalCapable: false,
    fallbackPriority: 1,
    description: "Fournisseur principal haute performance. Clé injectée de façon sécurisée côté serveur. Idéal pour compréhension multilingue et raisonnement complexe.",
  },
  {
    id: 'groq',
    name: 'Groq Cloud (Llama 3 / Mixtral)',
    providerType: 'open_source',
    status: 'standby',
    defaultModel: 'llama-3.3-70b-versatile',
    availableModels: ['llama-3.3-70b-versatile', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
    latencyMs: 120,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 30,
    currentRpm: 0,
    isConfigured: true,
    isLocalCapable: false,
    fallbackPriority: 2,
    description: "Fournisseur ultra-rapide LPUs pour réponses instantanées et fallback d'urgence quand le quota principal sature.",
  },
  {
    id: 'mistral',
    name: 'Mistral AI / Hugging Face Inference',
    providerType: 'open_source',
    status: 'active',
    defaultModel: 'mistral-small-latest',
    availableModels: ['mistral-small-latest', 'codestral-2501'],
    latencyMs: 410,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 20,
    currentRpm: 3,
    isConfigured: true,
    isLocalCapable: false,
    fallbackPriority: 3,
    description: "Modèle compact open source réputé pour l'exactitude syntaxique et la compression de contexte.",
  },
  {
    id: 'ollama_local',
    name: 'Ollama / vLLM (Souveraineté Locale)',
    providerType: 'local_server',
    status: 'active',
    defaultModel: 'qwen2.5:7b-instruct-q4_K_M',
    availableModels: ['qwen2.5:7b-instruct-q4_K_M', 'llama3.2:3b', 'mistral:7b'],
    latencyMs: 650,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 9999, // Pas de limite externe
    currentRpm: 4,
    isConfigured: true,
    isLocalCapable: true,
    fallbackPriority: 4,
    description: "Exécution locale sur serveur hôte Niamey. Aucune donnée ne quitte le territoire sahélien. 100% résistant aux coupures de liaison internationale.",
  },
];

export const INITIAL_EVENTS: EcosystemEvent[] = [
  {
    id: 'ev-9921',
    timestamp: '10:44:02',
    sourceService: 'Barewa Mobility',
    targetService: 'Barewa Maps',
    eventType: 'route.geocode.reverse',
    payloadSummary: 'Calcul d itinéraire Niamey Grand Marché -> Rond-point Francophonie (4.8 km)',
    status: 'delivered',
    durationMs: 48,
  },
  {
    id: 'ev-9920',
    timestamp: '10:43:45',
    sourceService: 'Barewa Health',
    targetService: 'Barewa AI',
    eventType: 'triage.inference.clinical',
    payloadSummary: 'Synthèse symptômes signalés (Zinder) pour orientation dispensaire de proximité',
    status: 'delivered',
    durationMs: 312,
  },
  {
    id: 'ev-9919',
    timestamp: '10:42:10',
    sourceService: 'Barewa Météo',
    targetService: 'Ecosystem EventBus',
    eventType: 'climate.alert.duststorm',
    payloadSummary: 'Alerte tempête de sable niveau 2 émise sur axe Tahoua-Agadez',
    status: 'delivered',
    durationMs: 22,
  },
  {
    id: 'ev-9918',
    timestamp: '10:41:03',
    sourceService: 'Barewa Store',
    targetService: 'Barewa Mobility',
    eventType: 'delivery.dispatch.request',
    payloadSummary: 'Demande coursier express pour commande #BS-4492 (Maradi Centre)',
    status: 'delivered',
    durationMs: 85,
  },
  {
    id: 'ev-9917',
    timestamp: '10:39:55',
    sourceService: 'Barewa Académie',
    targetService: 'Barewa Core Database',
    eventType: 'course.progress.batch',
    payloadSummary: 'Synchronisation différée de 84 devoirs hors-ligne (Gazaoua/Aguié)',
    status: 'delivered',
    durationMs: 140,
  },
  {
    id: 'ev-9916',
    timestamp: '10:38:12',
    sourceService: 'Barewa Jobs',
    targetService: 'Barewa AI',
    eventType: 'match.skill.vector',
    payloadSummary: 'Appariement profil électricien solaire avec appel d offre maraîchage',
    status: 'delivered',
    durationMs: 290,
  },
];

export const INITIAL_QUEUES: ServiceQueue[] = [
  {
    id: 'q-sms',
    name: 'Queue Notifications SMS & GSM',
    purpose: 'Envoi d alertes météo et codes de sécurité OTP par passerelles locales',
    pendingCount: 14,
    processed24h: 3820,
    failureRate: 0.4,
    status: 'active',
  },
  {
    id: 'q-offline',
    name: 'Queue Synchronisation PWA Hors-ligne',
    purpose: 'Réconciliation des données locales synchronisées dès le retour de connectivité',
    pendingCount: 68,
    processed24h: 9140,
    failureRate: 0.1,
    status: 'active',
  },
  {
    id: 'q-webhooks',
    name: 'Queue Webhooks & Intégrations Partenaires',
    purpose: 'Transmission des flux vers opérateurs télécoms, pharmacies et transporteurs',
    pendingCount: 3,
    processed24h: 1850,
    failureRate: 0.0,
    status: 'active',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Admin',
    action: 'Démarrage Session QG',
    target: 'Cockpit Central',
    details: 'Session initialisée avec succès depuis le terminal sécurisé Niamey.',
    ipAddress: '197.214.120.45',
    timestamp: '11/09/2026 10:40:12',
    severity: 'normal',
    status: 'success',
  },
  {
    id: 'log-002',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Admin',
    action: 'Audit de Routage IA',
    target: 'AI Router Engine',
    details: 'Vérification du modèle par défaut (Gemini 2.5 Flash) et des fallbacks Groq/Mistral.',
    ipAddress: '197.214.120.45',
    timestamp: '11/09/2026 10:32:00',
    severity: 'sensitive',
    status: 'success',
  },
  {
    id: 'log-003',
    adminName: 'Système Automatique QG',
    role: 'Sentinel SecOps',
    action: 'Blocage IP Suspecte',
    target: 'Pare-feu Réseau',
    details: 'Isolation temporaire de 102.164.88.12 suite à de multiples requêtes non conformes.',
    ipAddress: '127.0.0.1 (Internal)',
    timestamp: '11/09/2026 08:30:15',
    severity: 'critical',
    status: 'blocked',
  },
  {
    id: 'log-004',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Admin',
    action: 'Mise à jour Registre Services',
    target: 'Barewa Mobility v1.2.0',
    details: 'Validation de conformité des points de terminaison REST et WebSocket.',
    ipAddress: '197.214.120.45',
    timestamp: '10/09/2026 21:15:30',
    severity: 'normal',
    status: 'success',
  },
];

export const INITIAL_SESSIONS: SecuritySession[] = [
  {
    id: 'sess-current',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Administrateur QG',
    ipAddress: '197.214.120.45 (Orange Niger / Niamey)',
    location: 'Niamey, République du Niger',
    device: 'Poste de Contrôle Principal (Chrome / Linux x86_64)',
    loginTime: '11/09/2026 08:15',
    lastActive: 'À l instant',
    isCurrent: true,
  },
  {
    id: 'sess-mobile-ops',
    adminName: 'Ingénieur Astreinte QG',
    role: 'Opérateur Technique',
    ipAddress: '102.164.92.18 (Airtel Niger / Zinder)',
    location: 'Zinder, République du Niger',
    device: 'Terminal Mobile de Terrain (Android PWA QG)',
    loginTime: '11/09/2026 06:40',
    lastActive: 'Il y a 14 min',
    isCurrent: false,
  },
];

export const INITIAL_ADMINS: AdministratorAccount[] = [
  {
    id: 'adm-01',
    name: 'Architecte Principal BAREWA',
    email: 'taktaktaxi2026@gmail.com',
    role: 'super_admin',
    status: 'active',
    lastLogin: 'À l instant',
    twoFactorEnabled: true,
    allowedIps: ['197.214.120.45', '127.0.0.1'],
  },
  {
    id: 'adm-02',
    name: 'Responsable Sécurité & RLS',
    email: 'secops@barewa.ne',
    role: 'secops',
    status: 'active',
    lastLogin: '10/09/2026 19:40',
    twoFactorEnabled: true,
    allowedIps: ['*'],
  },
  {
    id: 'adm-03',
    name: 'Auditeur Conformité & Données',
    email: 'audit@barewa.ne',
    role: 'auditor',
    status: 'active',
    lastLogin: '09/09/2026 14:12',
    twoFactorEnabled: false,
    allowedIps: ['*'],
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  ecosystemName: 'Écosystème BAREWA — Sahel Numérique',
  environment: 'production',
  globalMaintenanceMode: false,
  sahelLowBandwidthMode: true, // Optimisé pour 2G/3G
  telemetryIntervalSeconds: 15,
  sessionTimeoutMinutes: 30,
  alertEmailRecipient: 'taktaktaxi2026@gmail.com',
  rateLimitPerMinute: 600,
  enforceRls: true,
  primaryTimezone: 'Africa/Niamey (UTC+1)',
  isDemoMode: true, // Clearly stated: Demo/Simulation mode for V1
};
