import {
  BarewaService,
  BarewaAlert,
  SecuritySession,
  ActivityLog,
  AIProvider,
  EcosystemEvent,
  ServiceQueue,
  AdministratorAccount,
  SystemSettings,
  BarewaAgent,
  DevForceMission,
  Conversation,
  ApprovalRequest,
  BAPEvent,
  BAPProtocolConfig,
} from '@/types/barewa';

export const INITIAL_SERVICES: BarewaService[] = [
  {
    id: 'srv-core-ai',
    code: 'BAREWA_AI',
    name: 'Barewa AI',
    description: "Couche d'intelligence contextuelle sahélienne, assistance multilingue (Hausa, Zarma, Français) et raisonnement distribué.",
    category: 'intelligence',
    status: 'online',
    version: 'v1.4.0',
    uptimePercent: 99.98,
    lastPingTime: 'Il y a 3s',
    endpointUrl: 'https://ai.barewa.ne/v1/router',
    connectionMode: 'REST_API',
    activeUsers24h: 3840,
    requestsPerMinute: 142,
    errorRatePercent: 0.04,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey (West-Africa)',
    tags: ['Gemini', 'Mistral', 'Ollama', 'NLP'],
  },
  {
    id: 'srv-academie',
    code: 'BAREWA_ACADEMIE',
    name: 'Barewa Académie',
    description: "Plateforme éducative, formations techniques, e-learning hors-ligne et certification pour la jeunesse du Sahel.",
    category: 'social',
    status: 'online',
    version: 'v1.1.2',
    uptimePercent: 99.92,
    lastPingTime: 'Il y a 12s',
    endpointUrl: 'https://academie.barewa.ne/api',
    connectionMode: 'REST_API',
    activeUsers24h: 12450,
    requestsPerMinute: 88,
    errorRatePercent: 0.12,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey / Zinder',
    tags: ['Éducation', 'PWA', 'Hors-ligne', 'Sahel'],
  },
  {
    id: 'srv-health',
    code: 'BAREWA_HEALTH',
    name: 'Barewa Health',
    description: "Dossier médical d'urgence, télé-orientation, carnets de vaccination et réseau d'officines pharmaceutiques de proximité.",
    category: 'social',
    status: 'online',
    version: 'v1.0.8',
    uptimePercent: 99.99,
    lastPingTime: 'Il y a 5s',
    endpointUrl: 'https://health.barewa.ne/api/v1',
    connectionMode: 'REST_API',
    activeUsers24h: 2190,
    requestsPerMinute: 34,
    errorRatePercent: 0.01,
    isMaintenance: false,
    isEnabled: true,
    region: 'Maradi / Niamey',
    tags: ['Santé', 'Sécurité Données', 'Pharmacies', 'Urgence'],
  },
  {
    id: 'srv-meteo',
    code: 'BAREWA_METEO',
    name: 'Barewa Météo',
    description: "Système agrométéorologique sahélien, prévisions pluviométriques, alertes canicule et tempêtes de sable pour agriculteurs.",
    category: 'core',
    status: 'online',
    version: 'v2.0.1',
    uptimePercent: 99.95,
    lastPingTime: 'Il y a 8s',
    endpointUrl: 'https://meteo.barewa.ne/telemetry',
    connectionMode: 'WEBSOCKET',
    activeUsers24h: 18400,
    requestsPerMinute: 210,
    errorRatePercent: 0.08,
    isMaintenance: false,
    isEnabled: true,
    region: 'Sahel Regional Grid',
    tags: ['Agrométéo', 'Alertes SMS', 'Satellites', 'Climat'],
  },
  {
    id: 'srv-store',
    code: 'BAREWA_STORE',
    name: 'Barewa Store',
    description: "Place de marché marchande sahélienne, logistique de distribution locale, paiements en FCFA et micro-commerce.",
    category: 'commerce',
    status: 'degraded',
    version: 'v0.9.4',
    uptimePercent: 98.85,
    lastPingTime: 'Il y a 45s',
    endpointUrl: 'https://store.barewa.ne/api/v2',
    connectionMode: 'REST_API',
    activeUsers24h: 5310,
    requestsPerMinute: 95,
    errorRatePercent: 2.14,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey / Tahoua',
    tags: ['E-commerce', 'Mobile Money', 'Artisanat', 'Logistique'],
  },
  {
    id: 'srv-maps',
    code: 'BAREWA_MAPS',
    name: 'Barewa Maps',
    description: "Système de géocodage descriptif, cartographie collaborative hors-ligne et points d'intérêt pour les villes et routes sahéliennes.",
    category: 'infrastructure',
    status: 'online',
    version: 'v1.0.3',
    uptimePercent: 99.91,
    lastPingTime: 'Il y a 14s',
    endpointUrl: 'https://maps.barewa.ne/tiles',
    connectionMode: 'DIRECT_DB',
    activeUsers24h: 8900,
    requestsPerMinute: 310,
    errorRatePercent: 0.05,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey Server CDN',
    tags: ['SIG', 'OpenStreetMap', 'Offline Tiles', 'Routage'],
  },
  {
    id: 'srv-mobility',
    code: 'BAREWA_MOBILITY',
    name: 'Barewa Mobility',
    description: "Plateforme de mise en relation taxi-motos, transport collectif interurbain et acheminement de colis inter-villes.",
    category: 'mobility',
    status: 'online',
    version: 'v1.2.0',
    uptimePercent: 99.88,
    lastPingTime: 'Il y a 6s',
    endpointUrl: 'https://mobility.barewa.ne/ws',
    connectionMode: 'WEBSOCKET',
    activeUsers24h: 6720,
    requestsPerMinute: 180,
    errorRatePercent: 0.15,
    isMaintenance: false,
    isEnabled: true,
    region: 'Niamey & Corridors',
    tags: ['Transports', 'Géolocalisation', 'Taxis', 'Fret'],
  },
  {
    id: 'srv-jobs',
    code: 'BAREWA_JOBS',
    name: 'Barewa Jobs',
    description: "Bourse d'opportunités, mise en relation pour artisans, jeunes diplômés, missions ponctuelles et recrutement sahélien.",
    category: 'social',
    status: 'online',
    version: 'v1.0.0',
    uptimePercent: 99.90,
    lastPingTime: 'Il y a 22s',
    endpointUrl: 'https://jobs.barewa.ne/graphql',
    connectionMode: 'REST_API',
    activeUsers24h: 4120,
    requestsPerMinute: 42,
    errorRatePercent: 0.02,
    isMaintenance: false,
    isEnabled: true,
    region: 'Sahel Ouest',
    tags: ['Emploi', 'Artisans', 'Talents', 'Recrutement'],
  },
];

export const INITIAL_ALERTS: BarewaAlert[] = [
  {
    id: 'alt-01',
    title: 'Taux de latence accru sur passerelle SMS Barewa Météo',
    message: "Le relais SMS opérateur Orange/Airtel Niger accuse une latence moyenne de 12.4s pour la diffusion des alertes météo aux zones rurales.",
    severity: 'warning',
    serviceId: 'srv-meteo',
    serviceName: 'Barewa Météo',
    timestamp: '11/09/2026 10:14',
    isResolved: false,
    isAcknowledged: true,
    suggestedAction: "Basculer temporairement sur la file d'attente secondaire Moov Africa ou prioriser le canal WhatsApp/PWA.",
  },
  {
    id: 'alt-02',
    title: 'Quota horaire API Gemini Cloud à 82%',
    message: "La consommation du free-tier Google Gemini s'approche du seuil critique de 15 RPM. Le routeur IA prépare le basculement automatique.",
    severity: 'critical',
    serviceId: 'srv-core-ai',
    serviceName: 'Barewa AI',
    timestamp: '11/09/2026 09:58',
    isResolved: false,
    isAcknowledged: false,
    suggestedAction: "Activer le fallback Groq/Llama 3 ou orienter les requêtes simples vers l'instance locale Ollama.",
  },
  {
    id: 'alt-03',
    title: 'Tentative de connexion par force brute bloquée',
    message: "14 tentatives échouées sur le point d'administration en provenance de l'IP 102.164.88.12. IP temporairement bannie pour 24 heures.",
    severity: 'warning',
    serviceId: 'srv-core-security',
    serviceName: 'Barewa QG Sécurité',
    timestamp: '11/09/2026 08:30',
    isResolved: true,
    isAcknowledged: true,
    sourceIp: '102.164.88.12',
    suggestedAction: "Vérifier la politique de verrouillage d'IP et inspecter les requêtes similaires.",
  },
  {
    id: 'alt-04',
    title: 'Synchronisation PostgreSQL Supabase réussie',
    message: "La sauvegarde incrémentale et le snapshot des tables RLS ont été exécutés avec succès sans interruption de service.",
    severity: 'info',
    serviceId: 'srv-core-db',
    serviceName: 'Barewa Core Database',
    timestamp: '11/09/2026 06:00',
    isResolved: true,
    isAcknowledged: true,
  },
];

export const INITIAL_AI_PROVIDERS: AIProvider[] = [
  {
    id: 'gemini',
    name: 'Google Gemini (Native Engine)',
    providerType: 'cloud_free',
    status: 'active',
    defaultModel: 'gemini-2.5-flash',
    availableModels: ['gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemini-2.5-pro'],
    latencyMs: 340,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 15,
    currentRpm: 12,
    isConfigured: true,
    isLocalCapable: false,
    fallbackPriority: 1,
    description: "Fournisseur principal haute performance. Clé injectée de façon sécurisée côté serveur. Idéal pour compréhension multilingue et raisonnement complexe.",
  },
  {
    id: 'groq',
    name: 'Groq Cloud (Llama 3 / Mixtral)',
    providerType: 'open_source',
    status: 'standby',
    defaultModel: 'llama-3.3-70b-versatile',
    availableModels: ['llama-3.3-70b-versatile', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
    latencyMs: 120,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 30,
    currentRpm: 0,
    isConfigured: true,
    isLocalCapable: false,
    fallbackPriority: 2,
    description: "Fournisseur ultra-rapide LPUs pour réponses instantanées et fallback d'urgence quand le quota principal sature.",
  },
  {
    id: 'mistral',
    name: 'Mistral AI / Hugging Face Inference',
    providerType: 'open_source',
    status: 'active',
    defaultModel: 'mistral-small-latest',
    availableModels: ['mistral-small-latest', 'codestral-2501'],
    latencyMs: 410,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 20,
    currentRpm: 3,
    isConfigured: true,
    isLocalCapable: false,
    fallbackPriority: 3,
    description: "Modèle compact open source réputé pour l'exactitude syntaxique et la compression de contexte.",
  },
  {
    id: 'ollama_local',
    name: 'Ollama / vLLM (Souveraineté Locale)',
    providerType: 'local_server',
    status: 'active',
    defaultModel: 'qwen2.5:7b-instruct-q4_K_M',
    availableModels: ['qwen2.5:7b-instruct-q4_K_M', 'llama3.2:3b', 'mistral:7b'],
    latencyMs: 650,
    costPer1kTokensCFA: 0.0,
    freeTierRpmLimit: 9999, // Pas de limite externe
    currentRpm: 4,
    isConfigured: true,
    isLocalCapable: true,
    fallbackPriority: 4,
    description: "Exécution locale sur serveur hôte Niamey. Aucune donnée ne quitte le territoire sahélien. 100% résistant aux coupures de liaison internationale.",
  },
];

export const INITIAL_EVENTS: EcosystemEvent[] = [
  {
    id: 'ev-9921',
    timestamp: '10:44:02',
    sourceService: 'Barewa Mobility',
    targetService: 'Barewa Maps',
    eventType: 'route.geocode.reverse',
    payloadSummary: 'Calcul d itinéraire Niamey Grand Marché -> Rond-point Francophonie (4.8 km)',
    status: 'delivered',
    durationMs: 48,
  },
  {
    id: 'ev-9920',
    timestamp: '10:43:45',
    sourceService: 'Barewa Health',
    targetService: 'Barewa AI',
    eventType: 'triage.inference.clinical',
    payloadSummary: 'Synthèse symptômes signalés (Zinder) pour orientation dispensaire de proximité',
    status: 'delivered',
    durationMs: 312,
  },
  {
    id: 'ev-9919',
    timestamp: '10:42:10',
    sourceService: 'Barewa Météo',
    targetService: 'Ecosystem EventBus',
    eventType: 'climate.alert.duststorm',
    payloadSummary: 'Alerte tempête de sable niveau 2 émise sur axe Tahoua-Agadez',
    status: 'delivered',
    durationMs: 22,
  },
  {
    id: 'ev-9918',
    timestamp: '10:41:03',
    sourceService: 'Barewa Store',
    targetService: 'Barewa Mobility',
    eventType: 'delivery.dispatch.request',
    payloadSummary: 'Demande coursier express pour commande #BS-4492 (Maradi Centre)',
    status: 'delivered',
    durationMs: 85,
  },
  {
    id: 'ev-9917',
    timestamp: '10:39:55',
    sourceService: 'Barewa Académie',
    targetService: 'Barewa Core Database',
    eventType: 'course.progress.batch',
    payloadSummary: 'Synchronisation différée de 84 devoirs hors-ligne (Gazaoua/Aguié)',
    status: 'delivered',
    durationMs: 140,
  },
  {
    id: 'ev-9916',
    timestamp: '10:38:12',
    sourceService: 'Barewa Jobs',
    targetService: 'Barewa AI',
    eventType: 'match.skill.vector',
    payloadSummary: 'Appariement profil électricien solaire avec appel d offre maraîchage',
    status: 'delivered',
    durationMs: 290,
  },
];

export const INITIAL_QUEUES: ServiceQueue[] = [
  {
    id: 'q-sms',
    name: 'Queue Notifications SMS & GSM',
    purpose: 'Envoi d alertes météo et codes de sécurité OTP par passerelles locales',
    pendingCount: 14,
    processed24h: 3820,
    failureRate: 0.4,
    status: 'active',
  },
  {
    id: 'q-offline',
    name: 'Queue Synchronisation PWA Hors-ligne',
    purpose: 'Réconciliation des données locales synchronisées dès le retour de connectivité',
    pendingCount: 68,
    processed24h: 9140,
    failureRate: 0.1,
    status: 'active',
  },
  {
    id: 'q-webhooks',
    name: 'Queue Webhooks & Intégrations Partenaires',
    purpose: 'Transmission des flux vers opérateurs télécoms, pharmacies et transporteurs',
    pendingCount: 3,
    processed24h: 1850,
    failureRate: 0.0,
    status: 'active',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Admin',
    action: 'Démarrage Session QG',
    target: 'Cockpit Central',
    details: 'Session initialisée avec succès depuis le terminal sécurisé Niamey.',
    ipAddress: '197.214.120.45',
    timestamp: '11/09/2026 10:40:12',
    severity: 'normal',
    status: 'success',
  },
  {
    id: 'log-002',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Admin',
    action: 'Audit de Routage IA',
    target: 'AI Router Engine',
    details: 'Vérification du modèle par défaut (Gemini 2.5 Flash) et des fallbacks Groq/Mistral.',
    ipAddress: '197.214.120.45',
    timestamp: '11/09/2026 10:32:00',
    severity: 'sensitive',
    status: 'success',
  },
  {
    id: 'log-003',
    adminName: 'Système Automatique QG',
    role: 'Sentinel SecOps',
    action: 'Blocage IP Suspecte',
    target: 'Pare-feu Réseau',
    details: 'Isolation temporaire de 102.164.88.12 suite à de multiples requêtes non conformes.',
    ipAddress: '127.0.0.1 (Internal)',
    timestamp: '11/09/2026 08:30:15',
    severity: 'critical',
    status: 'blocked',
  },
  {
    id: 'log-004',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Admin',
    action: 'Mise à jour Registre Services',
    target: 'Barewa Mobility v1.2.0',
    details: 'Validation de conformité des points de terminaison REST et WebSocket.',
    ipAddress: '197.214.120.45',
    timestamp: '10/09/2026 21:15:30',
    severity: 'normal',
    status: 'success',
  },
];

export const INITIAL_SESSIONS: SecuritySession[] = [
  {
    id: 'sess-current',
    adminName: 'Architecte Principal BAREWA',
    role: 'Super Administrateur QG',
    ipAddress: '197.214.120.45 (Orange Niger / Niamey)',
    location: 'Niamey, République du Niger',
    device: 'Poste de Contrôle Principal (Chrome / Linux x86_64)',
    loginTime: '11/09/2026 08:15',
    lastActive: 'À l instant',
    isCurrent: true,
  },
  {
    id: 'sess-mobile-ops',
    adminName: 'Ingénieur Astreinte QG',
    role: 'Opérateur Technique',
    ipAddress: '102.164.92.18 (Airtel Niger / Zinder)',
    location: 'Zinder, République du Niger',
    device: 'Terminal Mobile de Terrain (Android PWA QG)',
    loginTime: '11/09/2026 06:40',
    lastActive: 'Il y a 14 min',
    isCurrent: false,
  },
];

export const INITIAL_ADMINS: AdministratorAccount[] = [
  {
    id: 'adm-01',
    name: 'Architecte Principal BAREWA',
    email: 'taktaktaxi2026@gmail.com',
    role: 'super_admin',
    status: 'active',
    lastLogin: 'À l instant',
    twoFactorEnabled: true,
    allowedIps: ['197.214.120.45', '127.0.0.1'],
  },
  {
    id: 'adm-02',
    name: 'Responsable Sécurité & RLS',
    email: 'secops@barewa.ne',
    role: 'secops',
    status: 'active',
    lastLogin: '10/09/2026 19:40',
    twoFactorEnabled: true,
    allowedIps: ['*'],
  },
  {
    id: 'adm-03',
    name: 'Auditeur Conformité & Données',
    email: 'audit@barewa.ne',
    role: 'auditor',
    status: 'active',
    lastLogin: '09/09/2026 14:12',
    twoFactorEnabled: false,
    allowedIps: ['*'],
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  ecosystemName: 'Écosystème BAREWA — Sahel Numérique',
  environment: 'production',
  globalMaintenanceMode: false,
  sahelLowBandwidthMode: true, // Optimisé pour 2G/3G
  telemetryIntervalSeconds: 15,
  sessionTimeoutMinutes: 30,
  alertEmailRecipient: 'taktaktaxi2026@gmail.com',
  rateLimitPerMinute: 600,
  enforceRls: true,
  primaryTimezone: 'Africa/Niamey (UTC+1)',
  isDemoMode: true, // Clearly stated: Demo/Simulation mode for V1
};

// ==========================================
// BAREWA DEV FORCE INITIAL DATA
// ==========================================

export const INITIAL_AGENTS: BarewaAgent[] = [
  {
    agent_id: 'DEV-001',
    name: 'Barewa DEV Agent',
    role: 'dev',
    unit: 'Barewa DEV Force',
    status: 'online',
    activityState: 'working',
    modelUsed: 'Google Gemini 2.5 Flash / Codestral',
    avatar: '👨💻',
    capabilities: [
      'Implémentation TypeScript/React',
      'Refactoring Next.js App Router',
      'Résolution de bugs & intégration API',
      'Adaptation mobile PWA offline-first',
    ],
    tools: ['Git Workspace', 'AST Parser', 'Next.js Compiler', 'Code Runner', 'Linter'],
    currentMissionId: 'BAREWA-TAXI-QR-001',
    lastActivity: 'Il y a 30s',
    authorizationLevel: 'L2_DEVELOPER',
    metrics: { tasksCompleted: 48, successRate: 98.2, avgLatencyMs: 420 },
  },
  {
    agent_id: 'ARCH-001',
    name: 'Barewa Architecte Système',
    role: 'architect',
    unit: 'Barewa DEV Force',
    status: 'online',
    activityState: 'idle',
    modelUsed: 'Google Gemini 2.5 Pro',
    avatar: '🏗️',
    capabilities: [
      'Conception modulaire découplée',
      'Garantie compatibilité BAREWA CORE',
      'Spécification protocoles inter-services (BAP)',
      'Évaluation de dette technique',
    ],
    tools: ['Architecture Matrix', 'UML Graph Builder', 'BAP Protocol Spec', 'ADR Writer'],
    currentMissionId: 'BAREWA-TAXI-QR-001',
    lastActivity: 'Il y a 2 min',
    authorizationLevel: 'L3_MAINTAINER',
    metrics: { tasksCompleted: 34, successRate: 100, avgLatencyMs: 680 },
  },
  {
    agent_id: 'DB-001',
    name: 'Barewa Database & RLS Sentinel',
    role: 'database',
    unit: 'Barewa DEV Force',
    status: 'online',
    activityState: 'waiting',
    modelUsed: 'Groq / Llama 3.3 70B',
    avatar: '🗄️',
    capabilities: [
      'Schématisation PostgreSQL / Supabase',
      'Écriture politiques Row Level Security (RLS)',
      'Optimisation index & requêtes faibles bandes',
      'Contrôle intégrité référentielle',
    ],
    tools: ['PostgreSQL Schema Inspector', 'Supabase RLS Validator', 'EXPLAIN Query Plan', 'Migration DDL Generator'],
    currentMissionId: 'BAREWA-TAXI-QR-001',
    lastActivity: 'Il y a 1 min',
    authorizationLevel: 'L3_MAINTAINER',
    metrics: { tasksCompleted: 62, successRate: 99.1, avgLatencyMs: 210 },
  },
  {
    agent_id: 'QA-001',
    name: 'Barewa QA & Test Engineer',
    role: 'qa',
    unit: 'Barewa DEV Force',
    status: 'online',
    activityState: 'thinking',
    modelUsed: 'Google Gemini 2.5 Flash',
    avatar: '🧪',
    capabilities: [
      'Génération tests unitaires & intégration',
      'Simulation réseau 2G / 3G à forte gigue',
      'Tests de régression sans impact existant',
      'Audit couverture de code',
    ],
    tools: ['Jest Runner', 'Playwright Headless', 'Network Throttle 2G/3G', 'Coverage Assessor'],
    currentMissionId: 'BAREWA-TAXI-QR-001',
    lastActivity: 'Il y a 45s',
    authorizationLevel: 'L2_DEVELOPER',
    metrics: { tasksCompleted: 53, successRate: 96.5, avgLatencyMs: 380 },
  },
  {
    agent_id: 'SEC-001',
    name: 'Barewa SecOps Guardian',
    role: 'security',
    unit: 'Barewa DEV Force',
    status: 'online',
    activityState: 'working',
    modelUsed: 'Mistral Small Latest',
    avatar: '🔐',
    capabilities: [
      'Audit de sécurité zéro-confiance (Zero-Trust)',
      'Détection fuites de secrets ou clés API',
      'Validation permissions minimales (Least Privilege)',
      'Vérification des demandes d approbation QG',
    ],
    tools: ['Secret Scanner', 'OWASP Rules Checker', 'Token Verifier', 'Approval Enforcer'],
    currentMissionId: 'BAREWA-TAXI-QR-001',
    lastActivity: 'Il y a 15s',
    authorizationLevel: 'L4_ADMIN_COCKPIT',
    metrics: { tasksCompleted: 89, successRate: 100, avgLatencyMs: 290 },
  },
  {
    agent_id: 'OPS-001',
    name: 'Barewa DevOps & Container Operator',
    role: 'devops',
    unit: 'Barewa DEV Force',
    status: 'online',
    activityState: 'idle',
    modelUsed: 'Ollama Local Niamey (Qwen 2.5)',
    avatar: '🚀',
    capabilities: [
      'Déploiement conteneurs Cloud Run',
      'Gestion caches PWA et assets statiques',
      'Supervision Heartbeat & télémétrie',
      'Bascule réseau de secours',
    ],
    tools: ['Docker Manager', 'CloudRun Deployer', 'Health Probe Checker', 'Heartbeat Sender'],
    currentMissionId: undefined,
    lastActivity: 'Il y a 3 min',
    authorizationLevel: 'L3_MAINTAINER',
    metrics: { tasksCompleted: 41, successRate: 97.8, avgLatencyMs: 490 },
  },
];

export const INITIAL_MISSIONS: DevForceMission[] = [
  {
    mission_id: 'BAREWA-TAXI-QR-001',
    title: 'Intégration Réservation Rapide & Paiement QR Vélo-Taxi',
    objective:
      'Ajouter la réservation express et le paiement sécurisé par QR Code dans Barewa Mobility avec mode hors-ligne sans impacter le moteur existant.',
    application: 'Barewa Mobility',
    priority: 'HIGH',
    risk: 'MEDIUM',
    status: 'IN_PROGRESS',
    assignedAgents: ['DEV-001', 'ARCH-001', 'DB-001', 'QA-001', 'SEC-001'],
    constraints: [
      'Ne pas modifier les tables existantes sans migration rétro-compatible',
      'Validation RLS obligatoire sur la table des courses',
      'Temps d exécution < 300ms sur connexion Edge/2G Niamey',
      'Autorisation préalable du QG requise pour toute écriture en base',
    ],
    progress: 68,
    prUrl: 'https://github.com/barewa/mobility/pull/42',
    testResults: { total: 24, passed: 24, failed: 0, coverage: '94.5%' },
    deploymentStatus: 'STAGING',
    conversationId: 'conv-team-warroom',
    createdAt: '11/09/2026 09:15',
    updatedAt: '11/09/2026 10:48',
    finalReport:
      'Architecture validée par ARCH-001. Table de réservation prête pour validation QG. Suite à approbation, déploiement sur staging.',
  },
  {
    mission_id: 'HEALTH-TRIAGE-OFFLINE',
    title: 'Synchronisation PWA Dossiers Cliniques Zinder',
    objective:
      'Permettre aux infirmiers de brousse de saisir les protocoles paludisme hors-ligne avec synchronisation incrémentale sécurisée.',
    application: 'Barewa Health',
    priority: 'CRITICAL',
    risk: 'LOW',
    status: 'COMPLETED',
    assignedAgents: ['DEV-001', 'DB-001', 'SEC-001'],
    constraints: [
      'Chiffrement local AES-GCM dans IndexedDB',
      'Audit log pour chaque accès aux dossiers médicaux',
    ],
    progress: 100,
    prUrl: 'https://github.com/barewa/health/pull/18',
    testResults: { total: 38, passed: 38, failed: 0, coverage: '98.0%' },
    deploymentStatus: 'PRODUCTION',
    conversationId: 'conv-health-triage',
    createdAt: '10/09/2026 14:00',
    updatedAt: '11/09/2026 07:30',
    finalReport:
      'Mission achevée avec succès. 14 dispensaires ruraux équipés. Zéro collision de synchronisation détectée.',
  },
  {
    mission_id: 'METEO-SMS-FALLBACK',
    title: 'Passerelle USSD & SMS Moov/Airtel pour Alertes Sécheresse',
    objective:
      'Créer un canal de diffusion bas-débit par SMS/USSD (*142#) pour les zones sahéliennes sans couverture smartphone.',
    application: 'Barewa Météo',
    priority: 'HIGH',
    risk: 'HIGH',
    status: 'WAITING_APPROVAL',
    assignedAgents: ['DEV-001', 'OPS-001', 'SEC-001'],
    constraints: [
      'Respecter les quotas de passerelle SMPP opérateur',
      'Validation obligatoire du budget 0 FCFA garanti',
    ],
    progress: 45,
    deploymentStatus: 'PENDING',
    conversationId: 'conv-meteo-ussd',
    createdAt: '11/09/2026 08:30',
    updatedAt: '11/09/2026 10:20',
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    conversation_id: 'conv-dev-individual',
    title: 'Chat Direct — 👨💻 DEV Agent',
    type: 'INDIVIDUAL',
    participants: ['user', 'DEV-001'],
    applicationConcerned: 'Barewa Mobility',
    mission_id: 'BAREWA-TAXI-QR-001',
    status: 'ACTIVE',
    createdAt: '11/09/2026 09:20',
    updatedAt: '11/09/2026 10:45',
    messages: [
      {
        id: 'msg-01',
        conversationId: 'conv-dev-individual',
        senderId: 'user',
        senderName: 'Moi (Architecte QG)',
        text: 'Analyse le problème de connexion et de réservation de Barewa Taxi.',
        timestamp: '09:20',
      },
      {
        id: 'msg-02',
        conversationId: 'conv-dev-individual',
        senderId: 'DEV-001',
        senderName: 'Barewa DEV Agent',
        senderRole: 'dev',
        senderAvatar: '👨💻',
        text: "J'analyse actuellement le repository Barewa Mobility. Le composant TaxiBooking fonctionne en mode REST mais perd la connexion en cas de micro-coupure réseau sahélienne (2G). Je préconise d'implémenter un cache optimiste IndexedDB et un bouton de réservation rapide par QR Code pour les chauffeurs.",
        timestamp: '09:21',
      },
      {
        id: 'msg-03',
        conversationId: 'conv-dev-individual',
        senderId: 'user',
        senderName: 'Moi (Architecte QG)',
        text: 'Très bien. Propose cette amélioration sous forme de mission structurée pour DEV FORCE.',
        timestamp: '09:22',
      },
      {
        id: 'msg-04',
        conversationId: 'conv-dev-individual',
        senderId: 'DEV-001',
        senderName: 'Barewa DEV Agent',
        senderRole: 'dev',
        senderAvatar: '👨💻',
        text: "Proposition formulée pour la mission #BAREWA-TAXI-QR-001. Vous pouvez cliquer sur [Créer la Mission] ci-dessous pour déclencher la mobilisation de toute l'équipe dans la War Room !",
        timestamp: '09:23',
        actionPayload: {
          type: 'MISSION_PROPOSAL',
          data: {
            title: 'Intégration Réservation Rapide & Paiement QR Vélo-Taxi',
            application: 'Barewa Mobility',
            priority: 'HIGH',
            risk: 'MEDIUM',
          },
        },
      },
    ],
  },
  {
    conversation_id: 'conv-team-warroom',
    title: 'DEV FORCE — WAR ROOM (Cellule Inter-Agents)',
    type: 'TEAM',
    participants: ['user', 'DEV-001', 'ARCH-001', 'DB-001', 'QA-001', 'SEC-001'],
    applicationConcerned: 'Barewa Mobility',
    mission_id: 'BAREWA-TAXI-QR-001',
    status: 'ACTIVE',
    createdAt: '11/09/2026 09:30',
    updatedAt: '11/09/2026 10:48',
    messages: [
      {
        id: 'wmsg-01',
        conversationId: 'conv-team-warroom',
        senderId: 'user',
        senderName: 'Moi (Architecte QG)',
        text: 'Nous devons ajouter une fonctionnalité de réservation dans Barewa Taxi. Analysez ensemble l architecture et proposez un plan.',
        timestamp: '09:30',
      },
      {
        id: 'wmsg-02',
        conversationId: 'conv-team-warroom',
        senderId: 'ARCH-001',
        senderName: 'Barewa Architecte Système',
        senderRole: 'architect',
        senderAvatar: '🏗️',
        text: "Architecture analysée. Règle absolue BAREWA : zéro régression. Nous devons ajouter un service modulaire 'BarewaTaxiReservation' découplé du dispatching central. J'invite DB-001 à évaluer le schéma relationnel requis.",
        timestamp: '09:31',
      },
      {
        id: 'wmsg-03',
        conversationId: 'conv-team-warroom',
        senderId: 'DEV-001',
        senderName: 'Barewa DEV Agent',
        senderRole: 'dev',
        senderAvatar: '👨💻',
        text: "J'ai besoin de l'analyse du schéma pour préparer le composant React et le hook useTaxiBooking.",
        timestamp: '09:33',
      },
      {
        id: 'wmsg-04',
        conversationId: 'conv-team-warroom',
        senderId: 'DB-001',
        senderName: 'Barewa Database Sentinel',
        senderRole: 'database',
        senderAvatar: '🗄️',
        text: "Voici les contraintes : la table 'barewa_taxi_trips' a besoin d une colonne 'qr_token' unique et d'une table enfant 'barewa_taxi_reservations'. Les politiques Row Level Security (RLS) doivent impérativement isoler les chauffeurs et les clients par auth.uid().",
        timestamp: '09:35',
      },
      {
        id: 'wmsg-05',
        conversationId: 'conv-team-warroom',
        senderId: 'DEV-001',
        senderName: 'Barewa DEV Agent',
        senderRole: 'dev',
        senderAvatar: '👨💻',
        text: "Merci DB-001. J'intègre le code TypeScript avec ces contraintes.",
        timestamp: '09:36',
      },
      {
        id: 'wmsg-06',
        conversationId: 'conv-team-warroom',
        senderId: 'SEC-001',
        senderName: 'Barewa SecOps Guardian',
        senderRole: 'security',
        senderAvatar: '🔐',
        text: "⚠️ Attention, cette modification touche à la structure de la base de données et aux accès RLS. Conformément aux directives BAREWA QG, cette opération nécessite impérativement une validation manuelle de l'Architecte QG dans le Centre d'Approbation !",
        timestamp: '09:37',
        requiresApproval: true,
        approvalId: 'APP-001',
      },
      {
        id: 'wmsg-07',
        conversationId: 'conv-team-warroom',
        senderId: 'QA-001',
        senderName: 'Barewa QA Engineer',
        senderRole: 'qa',
        senderAvatar: '🧪',
        text: "J'ai préparé une suite de 24 tests unitaires pour valider la génération des QR codes, l'isolation RLS et la résilience hors-ligne sur réseau 2G simulé. Tous les tests passent au vert (100%). En attente de l'approbation QG.",
        timestamp: '09:40',
      },
    ],
  },
];

export const INITIAL_APPROVALS: ApprovalRequest[] = [
  {
    id: 'APP-001',
    mission_id: 'BAREWA-TAXI-QR-001',
    requesterAgentId: 'DB-001',
    requesterAgentName: 'Barewa Database & RLS Sentinel',
    title: 'Migration Schéma PostgreSQL : Table barewa_taxi_reservations & RLS',
    description:
      'Création de la table de réservation express avec contraintes étrangères sur auth.users, index géospatial et règles RLS interdisant tout accès non authentifié.',
    targetResource: 'PostgreSQL Supabase (Production) — Table barewa_taxi_reservations',
    riskLevel: 'MEDIUM',
    status: 'PENDING',
    createdAt: '11/09/2026 09:38',
    proposedDiff: `-- Création de la table de réservation Barewa Taxi
CREATE TABLE IF NOT EXISTS public.barewa_taxi_reservations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trip_id UUID REFERENCES public.barewa_services(id) ON DELETE CASCADE,
    passenger_id UUID REFERENCES auth.users(id) ON DELETE RESTRICT,
    pickup_address TEXT NOT NULL,
    qr_token VARCHAR(64) UNIQUE NOT NULL,
    fare_cfa NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'picked_up', 'completed')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Activation RLS stricte
ALTER TABLE public.barewa_taxi_reservations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Passagers lisent uniquement leurs réservations"
ON public.barewa_taxi_reservations FOR SELECT
USING (auth.uid() = passenger_id);`,
  },
  {
    id: 'APP-002',
    mission_id: 'HEALTH-TRIAGE-OFFLINE',
    requesterAgentId: 'OPS-001',
    requesterAgentName: 'Barewa DevOps Operator',
    title: 'Déploiement Conteneur Production Cloud Run Niamey v1.2.1',
    description:
      'Déploiement du conteneur optimisé avec compression Brotli pour le cache PWA des 14 centres de santé de Zinder.',
    targetResource: 'Cloud Run Niamey Gateway — Barewa Health v1.0.8',
    riskLevel: 'LOW',
    status: 'APPROVED',
    decidedAt: '11/09/2026 07:25',
    decidedBy: 'taktaktaxi2026@gmail.com',
    decisionNotes: 'Conformité vérifiée, SLA 99.99% préservé.',
    createdAt: '11/09/2026 07:15',
  },
];

export const INITIAL_BAP_EVENTS: BAPEvent[] = [
  {
    id: 'bap-ev-01',
    timestamp: '09:30:10',
    agentId: 'ARCH-001',
    agentName: 'Barewa Architecte Système',
    agentRole: 'architect',
    eventType: 'TASK_STARTED',
    description: 'Mission #BAREWA-TAXI-QR-001 reçue du QG. Analyse de faisabilité initiée.',
    missionId: 'BAREWA-TAXI-QR-001',
    state: 'thinking',
  },
  {
    id: 'bap-ev-02',
    timestamp: '09:31:45',
    agentId: 'ARCH-001',
    agentName: 'Barewa Architecte Système',
    agentRole: 'architect',
    eventType: 'ANALYSIS',
    description: 'Architecture validée : patron modulaire sans régression sur BAREWA CORE.',
    missionId: 'BAREWA-TAXI-QR-001',
    state: 'working',
  },
  {
    id: 'bap-ev-03',
    timestamp: '09:33:12',
    agentId: 'DEV-001',
    agentName: 'Barewa DEV Agent',
    agentRole: 'dev',
    eventType: 'CODE_GENERATION',
    description: 'Écriture du composant TaxiBookingQR & intégration WebSocket.',
    missionId: 'BAREWA-TAXI-QR-001',
    state: 'working',
  },
  {
    id: 'bap-ev-04',
    timestamp: '09:35:04',
    agentId: 'DB-001',
    agentName: 'Barewa Database Sentinel',
    agentRole: 'database',
    eventType: 'SCHEMA_CHECK',
    description: 'Conception de la table barewa_taxi_reservations et des règles RLS auth.uid().',
    missionId: 'BAREWA-TAXI-QR-001',
    state: 'working',
  },
  {
    id: 'bap-ev-05',
    timestamp: '09:37:30',
    agentId: 'SEC-001',
    agentName: 'Barewa SecOps Guardian',
    agentRole: 'security',
    eventType: 'APPROVAL_REQUIRED',
    description: 'Alerte sécurité : demande d approbation requise pour modification du schéma DDL.',
    missionId: 'BAREWA-TAXI-QR-001',
    state: 'approval_requested',
  },
  {
    id: 'bap-ev-06',
    timestamp: '09:40:15',
    agentId: 'QA-001',
    agentName: 'Barewa QA Engineer',
    agentRole: 'qa',
    eventType: 'TEST_RUN',
    description: '24/24 tests passés avec succès. Couverture : 94.5%. En attente de décision QG.',
    missionId: 'BAREWA-TAXI-QR-001',
    state: 'waiting',
  },
];

export const INITIAL_BAP_CONFIG: BAPProtocolConfig = {
  version: 'v1.0-bap-sahel',
  gatewayStatus: 'HEALTHY',
  primaryAdapter: 'crewai',
  registeredUnits: [
    {
      id: 'unit-devforce-01',
      name: 'BAREWA DEV FORCE (CrewAI Multi-Agent Fleet)',
      adapterType: 'CrewAI Adapter v0.102 (Découplé & Interchangeable)',
      agentCount: 6,
      heartbeatIntervalSec: 15,
      status: 'online',
    },
    {
      id: 'unit-local-worker',
      name: 'BAREWA Niamey Local Edge Worker',
      adapterType: 'Ollama Native LPU / vLLM',
      agentCount: 1,
      heartbeatIntervalSec: 30,
      status: 'online',
    },
  ],
  memoryStats: {
    globalEntries: 184,
    unitEntries: 64,
    agentEntries: 42,
    conversationEntries: 21,
    missionEntries: 12,
    auditEntries: 98,
  },
};

